# Number of CPU cores to use for Nginx worker processes
worker_processes 1;

events {
    # Maximum number of simultaneous connections per worker process
    worker_connections 1024; 
}

http {
    # Include MIME types for file extensions
    include mime.types;

    # Upstream block to define a cluster of Go application servers
    upstream go_cluster {
        # Load balancing method: least connections
        least_conn;
        server 127.0.0.1:8081;
        server 127.0.0.1:8082;
        server 127.0.0.1:8083;
    }

    server {
        # Listen on port 8080 for incoming HTTP requests
        listen 8080;
        # Define the server name (hostname) for this server block
        # Eg: If on VPS, you can set it to your domain name or IP address
        server_name localhost;

        # Define the location block for the root URL path
        # This block will proxy requests to the Go application cluster defined in the upstream block
        location / {
            proxy_pass http://go_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
